### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vorg** [UCC-Organism/crosswalk-odroid-ucc#1]
I'm trying to run the build on OSX and I've got the following error at the very end

```
[apkbuilder] Creating app-unsigned.apk for release...


jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2041-01-13) or after any future revocation date.

Traceback (most recent call last):
  File "scripts/gyp/finalize_apk.py", line 65, in <module>
    sys.exit(main())
  File "scripts/gyp/finalize_apk.py", line 58, in main
    AlignApk(options.android_sdk_root, signed_apk_path, options.final_apk_path)
  File "scripts/gyp/finalize_apk.py", line 39, in AlignApk
    build_utils.CheckCallDie(align_cmd)
  File "/Users/vorg/Workspace/var-uccorganism/crosswalk-odroid-ucc/scripts/gyp/util/build_utils.py", line 58, in CheckCallDie
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=cwd)
  File "/Users/vorg/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/vorg/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

My `setenv.sh`

``` shell
#var
ANT=/Users/vorg/Dev/ant/
ANDROID=/Users/vorg/Dev/adt/sdk/
XWALK=/Users/vorg/Workspace/var-uccorganism/crosswalk-odroid-ucc/
#ANT
export PATH=$ANT/bin:$PATH
#ANDROID
export PATH=$ANDROID:$PATH
export PATH=$ANDROID/tools:$PATH
export PATH=$ANDROID/platform-tools:$PATH
#CROSSWALK
export PATH=$XWALK:$PATH
```

**Comment by gauthiier** [comment]
I've updated the code with a fix for this "AlignApk" error. 
1. Pull the newest version.
2. Make sure you have android Build-Tools 20 -- '$ANDROID'/build-tools/20.0.0

fix is in scripts/gyp/finalize_apk.py - line 34
->  os.path.join(android_sdk_root, 'build-tools', '20.0.0', 'zipalign'),
